version: '3.5'

services:

  poc-tf-example-api:
    image: poc-tf-example-api:latest
    container_name: poc-tf-example-api
    build:
      context: ./stub-nodejs
      dockerfile: Dockerfile
    env_file:
      - .env
    # volumes:
    #   - './stub-nodejs:/usr/src/app:delegated'
    ports:
      - '8200:8200'
